import { useState, useEffect } from 'react';
import { useHistory } from 'react-router';
import { Link } from 'react-router-dom';

/**
 * @component
 * @name Pagination
 * @description A reusable pagination component.
 * @param {object} props
 * @param {number} props.totalPosts - The total retrieved data from a source (ex: endPoint).
 * @param {number} props.postsPerPage - The total elements to be displayed in every single page.
 * @param {string} props.pageName - The name of the page that shows in the url.
 * @param {object} [props.triggerFunction] - A function to fetch data inside the use effect hook & causes a component rerender.
 */
const Pagination = ({ totalPosts, postsPerPage, pageName, triggerFunction }) => {
  const history = useHistory();

  /** @typedef {number} totalPages - The total number of pages. */
  const totalPages = totalPosts / postsPerPage;

  /** @typedef {number} pager - The number of pagesLinks to show on the screen. */
  const pager = 12;

  /** @typedef {number} pagerShifts - The number of times the pager can shift/slide */
  const pagerShifts = Math.ceil(totalPages / pager);

  /** @typedef {number} startIndex - The pager start index. */
  const [startIndex, setStartIdx] = useState(0);

  /** @typedef {number} endIndex - The pager end index. */
  const [endIndex] = useState(startIndex + pager);

  /** @typedef {number} currentPage - The current page number. */
  const [currentPage, setCurrentPage] = useState(1);

  /** @typedef {number} resetPage - The value used to guide the pager where to show up. */
  const resetPage = parseInt(window.location.search.slice(6));

  useEffect(() => {
    /**
     * @function resetPagerBoundaries
     * @description Resets the pager start & end according to the current active page.
     * @example
     * ex: pager = 5;
     * if (currentPage >= 6) {
     *  setStartIdx(5); // ((index * pager) => (1 * 5)) and so on...
     * }
     */
    const resetPagerBoundaries = () => {
      if (!resetPage) {
        setCurrentPage(1);
      } else {
        setCurrentPage(resetPage);
      }
      for (let i = 0; i < pagerShifts; i++) {
        if (currentPage >= i * pager + 1) {
          setStartIdx(i * pager);
        }
      }
    };
    resetPagerBoundaries();
    triggerFunction();
  }, [currentPage]);

  /** @typedef {Array} pagesLinks - A placeholder for all autogenerated pagesLinks. */
  let pagesLinks = [];

  /**
   * @function generatePagesLinks
   * @description Generates pages links (the numbered buttons).
   */
  const generatePagesLinks = () => {
    for (let i = 0; i < totalPages; i++) {
      const link = (
        <Link
          key={i}
          to={`/${pageName}?page=${i + 1}`}
          className='pageLink'
          onClick={(e) => {
            setCurrentPage(i + 1);
            scrollToTop();
          }}
        >
          {i + 1}
        </Link>
      );
      pagesLinks.push(link);
    }
  };
  generatePagesLinks();

  /**
   * @function handlePrev
   * @description Goes to the previous page.
   * @param {object} e - The previous button event handler.
   */
  const handlePrev = (e) => {
    e.preventDefault();
    if (currentPage > 1 && currentPage <= totalPages) {
      setCurrentPage((currentPage) => currentPage - 1);
      history.push(`/${pageName}?page=${currentPage - 1}`);
    }
    if (!resetPage) {
      setCurrentPage(1);
    }
  };

  /**
   * @function handleNext
   * @description Goes to the next page.
   * @param {object} e - The next button event handler.
   */
  const handleNext = (e) => {
    e.preventDefault();
    if (currentPage >= 1 && currentPage < totalPages) {
      setCurrentPage((currentPage) => currentPage + 1);
      history.push(`/${pageName}?page=${currentPage + 1}`);
    }
    if (!resetPage) {
      setCurrentPage(2);
    }
  };

  /**
   * @function handlePagerShifts
   * @description Shifts/Slides the pager to the left/right.
   * @param {object} e - The shift button event handler.
   */
  const handlePagerShifts = (e) => {
    e.preventDefault();
    if (e.target.className.startsWith('prev')) {
      setStartIdx(startIndex - 12);
      if (startIndex == 0) {
        setStartIdx(0);
      }
    }
    if (e.target.className.startsWith('next')) {
      setStartIdx(startIndex + 12);
      if (totalPages - startIndex < pager) {
        setStartIdx(startIndex + 0);
      }
    }
  };

  /**
   * @function activatePageBtn
   * @description Gives some styles to the clicked page button/link
   * & waits a while until the document recognizes/loads the pagesLinks.
   */
  const activatePageBtn = () => {
    setTimeout(() => {
      const pagesLinks = document.querySelectorAll('.pageLink');
      for (let link of pagesLinks) {
        if (link.textContent == resetPage) {
          link.style.color = `#d4af37`;
          link.style.backgroundColor = `#212121`;
          link.style.border = `2px solid #d4af37`;
        } else {
          link.style.color = `white`;
          link.style.backgroundColor = `#070707`;
          link.style.border = `2px solid transparent`;
        }
      }
      if (pagesLinks[0] !== undefined && !resetPage) {
        pagesLinks[0].style.color = `#d4af37`;
        pagesLinks[0].style.backgroundColor = `#212121`;
        pagesLinks[0].style.border = `2px solid #d4af37`;
      }
    }, 500);
  };
  activatePageBtn();

  /**
   * @function scrollToTop
   * @description Scrolls to the very top of the page after every click
   * & waits a while until fetching data from the source.
   */
  const scrollToTop = () => {
    setTimeout(() => {
      window.scrollTo({
        top: 0,
        behavior: 'smooth',
      });
    }, 1500);
  };

  return (
    <div className='Pagination'>
      <Link
        to=''
        className='material-icons'
        onClick={(e) => {
          handlePrev(e);
          scrollToTop();
        }}
      >
        navigate_before
      </Link>

      <Link to='' className='prev material-icons' onClick={handlePagerShifts}>
        more_horiz
      </Link>

      {pagesLinks.splice(startIndex, endIndex).map((link) => link)}

      <Link to='' className='next material-icons' onClick={handlePagerShifts}>
        more_horiz
      </Link>

      <Link
        to=''
        className='material-icons'
        onClick={(e) => {
          handleNext(e);
          scrollToTop();
        }}
      >
        navigate_next
      </Link>
    </div>
  );
};

export default Pagination;
